services:
    password_booth:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./app.config:/app.config:ro
